### PR TITLE
Fixing bad usage of ConfigParser.

### PR DESCRIPTION
**Pull request by mio-moto**
Think functional.
Also the entire thing should be refactored using spaces, rather than tabs.
Other notes while working through it:
Don't use globals, you already have an object. A lot of code is completely out of place. Use logging.getLogger rather than print (logging-tress are way easier to manage). Reading from config all the time is a bad idea. I can understand to write into it, but that should be a buffer (configparser can write into buffered file-handlers iirc). The code is in general error-prone. The use of sections is bad for multiple sessions within one interpreter. (Same goes for globals.)

I'm working through your code and no offense, that one needs a bit of work to be way easier to maintain. Anyway, gj so far.

### CODE REVIEW

**Comment by mio-moto** [comment]
Also don't merge this yet, still looking through the most issues

**Comment by mio-moto** [comment]
This should do for now. Check out and merge at will.

**Comment by SmBe19** [comment]
Thank you for your contribution, I really appreciate it.

A few remarks (correct me if I'm wrong, I'm by far no expert in python):
- It doesn't matter whether one uses tabs or spaces. There is no reason to change the convention of an existing project.
- The globals I use are all constants, so I see no point in making them instance variables.
- As I understood the documentation, the config file is only read when you call `read(...)`, afterwards it's all in memory.
- What do you mean with sections?
- What's bad with that many try except blocks? Isn't this the "pythonic way" to just try and catch an exception instead of checking first?

**Comment by mio-moto** [comment]
## 1. Spaces.

Tabs are inconsistent in formatting, spaces have a fixed size. Also spaces are always the exact same size in encoding, while a tab is only creating visually space (and again, editor dependent). Refactoring from tabs to spaces is a minor change.

## 2. Globals

Again, concurrent oauth2util instances overwrite the global variables. There is no reason to keep them global in the first place.

## 3. ConfigParser

True, yet it's hard to retrace every time where there is no need to re-read the file. This includes the recheck on the timestamp of the config file, since there is no case where this should occur in the first place.

## 4. Sections

Your current use of sections is incomplete, as it should look something like this:

```
[app]
app_key = Something
app_secrept = SomethingSomething

[server]
server_mode = False

[so_concrete_user]
scope = identity
refreshable = True
refresh_token = receiving token
```

In general it is not adviceable to reuse the same request token across session, but the reddit api guidelines do not mention anything about cross session keys. Usually you should requery it anyway every time a new session / instance is created.

## 5. Try-Catch Blocks

No, it's not pythonic to "just do and catch errors". While the overhead is minimal, it is bad practice to write error-driven logic, especially when the introspection of those objects already has informations about what we're otherwise will get an exception from.

There is one other major problem which inspired me in rewriting it in the first place: https://github.com/SmBe19/praw-OAuth2Util/blob/master/OAuth2Util/OAuth2Util.py#L356

HTTPExceptions happen, especially on reddit, all the time and your Lib was trying to get a new refresh token. After seeing all those issues.

## 6. Other random notes

I've rewritten OAuthing on my own here: https://github.com/DarkMio/RedditRover/blob/master/core/BaseClass.py#L102-L141

Your server/terminal mode should maybe implement something simliar to ask for opening an url and inputting it, which solves some issues with working on dedicated machines.

**Pull request merged**
