### PR TITLE
Reversed unnecessary and unsecure practices

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SmBe19** [comment]
I merged the config handling of @Spedwards to allow a similar usage as before. What do you mean with unsecure practices?

**Comment by ghost** [comment]
@SmBe19 See http://programmers.stackexchange.com/questions/205606/strategy-for-keeping-secret-info-such-as-api-keys-out-of-source-control

**Comment by Spedwards** [comment]
Hopefully avinaash sees that.

**Comment by ghost** [comment]
You forgot to update the README, that has also been modified.

**Comment by avinassh** [comment]
@Spedwards you tagged me wrong. The top answer says:

> Don't put your secret information in your code. Put it into a configuration file which is read by your code at startup. Configuration files shouldn't be put on version control, unless they are the "factory defaults", and then they shouldn't have any private information.

And I don't see how I am breaking it. Or making people store it in the version control or in source

**Pull request closed without merging**
