### PR TITLE
Adds pip (and python packaging support) and extras!

### PR DESCRIPTION
**Pull request by avinassh**
- Now packaged this as a python module and also available on pip:
  
  ```
  pip install praw-oauth2util
  ```
- Also done bit of code refactoring. 
#### Changes:
- Config files `oauthappinfo.txt` and `oauthconfig.txt` are not required at all. Rather they will be sent at the time of object creation. Examples:
  1. `o = OAuth2Util.OAuth2Util(reddit_client, app_key=app_key, app_secret=app_secret)`
  2.  another:
     
     ```
         scope = ['identity', 'read']
         refreshable = False
         o = OAuth2Util.OAuth2Util(r, app_key=app_key,
                                   app_secret=app_secret,
                                   scope=scope,
                                   refreshable=refreshable)
     ```
- Config file `oauthtoken` is renamed to `praw-oauth-config.txt` and will be saved in home directory of the user. User can overide this by sending path to this file as a parameter `oauthtoken_configfile`

### CODE REVIEW

**Comment by Spedwards** [comment]
I believe you mean `pip install praw-oauth2util`,

Config files should remain but all in 1 file (see my commit). It just complicates things having them in the code as you may as well just do it all yourself.

Excluding the package, I'm personally against this getting added.

**Comment by avinassh** [comment]
I updated the `pip install` line

> Config files should remain but all in 1 file (see my commit). It just complicates things having them in the code as you may as well just do it all yourself

I don't understand. There are no config files in code now. the app specific config, is saved in `~/. praw-oauth-config.txt` which can be overridden. And I am following [XDG](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html). And for example, even Openshift, Github etc save configs in home directory.

**Comment by Spedwards** [comment]
Config files are a good thing. If you looked at my commit, you'd also notice that the config file can be used for other things. Also, XDG is nothing official, just a recommendation.

Github and Openshift can do whatever they want, they're actual companies with actual software. This is just a script, putting the config somewhere else (in my case a total different drive) is just a hassle.

Also, having the config in 1 location means you can only have 1 config file. I run 3-5 bots from my computer. Keep config files in the same directory as the script.

And I know you said you can specify a different location but a lot of people aren't and why bother with it when it's not necessary?

**Comment by avinassh** [comment]
The configurations are the app/script/bot specific, not relevant to module at all. The module should not worry about how are you saving and managing them. The script can very well handle all those. 

you can save the config wherever you want too. best would be saving them in OS Environments since these are access tokens. 

and you said, you can change the path however you want and by that way you can manage multiple bots.

**Comment by avinassh** [comment]
> Github and Openshift can do whatever they want, they're actual companies with actual software. This is just a script, putting the config somewhere else (in my case a total different drive) is just a hassle.

This is no longer a script now :smile:

**Comment by Spedwards** [comment]
Not what I meant, a script will call the package and the configs should be in the same directory as the script.

**Comment by avinassh** [comment]
> Not what I meant, a script will call the package and the configs should be in the same directory as the script.

Not that I disagree. 

So, whats problem with this:

```
# defaults to home directory
o = OAuth2Util.OAuth2Util(...)

# wherever you want
o = OAuth2Util.OAuth2Util(..., 'path_to_config')
```

The only difference is, one extra parameter call you have to do. 

And also, how do you say we manage when it is a Python Package? in main module and in tests. I am not sure you can use relative path, cos the module will reside in `site-packages`

**Comment by Spedwards** [comment]
It should be relative to the script that imports it. I have OAuth2Util.py in my Lib folder and all my scripts just import it and use it as you normally would. All files are relative to the individual bot.

**Comment by avinassh** [comment]
Yes, I understand that. I want to know how would you code it? (cos I don't know when modules come into the picture)

**Comment by Spedwards** [comment]
It wouldn't change. When you import a module, it gets seen as being in the same directory as the script that imported it.

**Comment by avinassh** [comment]
no, it depends on from where you are running the python. If you are in the current bot directory and run python it will be file. 

but when you run the same thing from other location or if you want to use supervisor for bot, the location of current directory changes.

**Comment by Spedwards** [comment]
I feel like an idiot because I just remembered that I run the following in all my scripts...

```
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
```

**Comment by SmBe19** [comment]
I think it makes more sense to place the tokens relative to the script as you can't use the same token for multiple scripts (because they are separate registered apps or their scopes differ).

Regarding the configuration I think it would be nice to either specify the values when creating the object (like you do now) or to use config files. With config files it would be easier to have a file with the app info (id & secret) in it, that you can add to .gitignore and not risk to accidentally commit if you want to publish your script.

**Comment by avinassh** [comment]
Yes, but it's better give that freedom to the user. He can place them in a file, home directory or OS environment.

The config is related to the app, not to the module. So app should handle the config files and not module. 

With these new changes, you are free to save the configs in the file :smile:

**Comment by SmBe19** [comment]
So the user should save the app id and app secret in a file and then load it prior to call OAuth2Utile?

**Comment by avinassh** [comment]
Yup. The user should do it, not module. The user may save it anywhere he pleases to. File on same directory, home directory, OS Environment etc. 

If you are unsure, you can ask this over at /r/learnpython

**Comment by SmBe19** [comment]
I think it's best to allow both methods (like praw does, you can specify username / password using r.login() or you can specify it in a praw.ini file).

**Comment by avinassh** [comment]
Yes, but see where praw recommends saving it: https://github.com/praw-dev/praw/blob/master/docs/pages/configuration_files.rst#config-file-locations

spoiler: it's in home directory of the user, not where the script is or being run.

**Comment by SmBe19** [comment]
So we should allow for a global, user and local config file? Don't you think that's a bit overkill? In most cases only the local config file will ever be used.

**Pull request merged**
